title: My Jekyll Site
description: A simple site using Jekyll on GitHub Pages
baseurl: "" # Leave this blank unless you're using a subpath
url: "https://skyl.name.ng" # Your custom domain or GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima

# Optional settings
plugins:
  - jekyll-feed
  
  title: My Jekyll Site
theme: minima
description: Monetag verification
monetag: 6c3c334d584b246a43b4047c71200ce4
